#My makefile need to have es règles $(NAME), all, clean, fclean et re.

CC := gcc
OBJS := ${SRC :c = o}
CFLAGS := -Wall -Werror -Wextra
SRCS := ft_isalpha.c ft_memcpy.c ft_bzero.c ft_isalnum.c ft_isdigit.c ft_isprint.c ft_strlen.c ft_isascii.c ft_memset.c ft_strlcat.c
DEEPS := libft.h
NAME := libft.a
all:
	${CC} ${CFlAGS} ${SRC}
clean:
	rm -rf *a.out
fclean:

re:
