#My makefile need to have es règles $(NAME), all, clean, fclean et re.

CC = gcc
OBJ = exe
CFLAGS = -Wall -Werror -Wextra
all:
	${CC} ${CFlAGS} tester.c ft_isalpha.c ft_memcpy.c ft_bzero.c ft_isalnum.c ft_isdigit.c ft_isprint.c ft_strlen.c ft_isascii.c ft_memset.c ft_strlcat.c
run:
	./a.out
clean:
	rm -rf *a.out
